import "./globals.css"; 
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* External CSS & JS via <link> and <script> must go in globals.css or _document */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Marcellus+SC&family=Monsieur+La+Doulaise&family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/css/common.css" />
        <link rel="stylesheet" href="/css/menu.css" />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
          defer
        ></script>

        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
